// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.WebApi.DAL;

namespace PersonalFinance.WebApi.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Final")
                        .HasColumnType("datetime2");

                    b.Property<int>("GanhoExtraId")
                        .HasColumnType("int");

                    b.Property<int>("GastosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicial")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatrimonioId")
                        .HasColumnType("int");

                    b.Property<int>("SalarioId")
                        .HasColumnType("int");

                    b.Property<double>("ValorGanho")
                        .HasColumnType("float");

                    b.Property<double>("ValorGasto")
                        .HasColumnType("float");

                    b.Property<double>("ValorSobra")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GanhoExtraId");

                    b.HasIndex("GastosId");

                    b.HasIndex("PatrimonioId");

                    b.HasIndex("SalarioId");

                    b.ToTable("Competencia");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeBanco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rendimento")
                        .HasColumnType("float");

                    b.Property<double>("ValorConta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ContaBancaria");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.GanhoExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataGanho")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GanhoExtra");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Gastos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataGasto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Investimentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeInvestimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rendimento")
                        .HasColumnType("float");

                    b.Property<double>("ValorInvestido")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Patrimonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<int>("InvestimentosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.Property<double>("ValorPatrimonio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("InvestimentosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Patrimonio");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Salario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<double>("Desconto1")
                        .HasColumnType("float");

                    b.Property<double>("Desconto2")
                        .HasColumnType("float");

                    b.Property<double>("Imposto")
                        .HasColumnType("float");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorAdicional")
                        .HasColumnType("float");

                    b.Property<double>("ValorBruto")
                        .HasColumnType("float");

                    b.Property<double>("ValorLiquido")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Salario");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Competencia", b =>
                {
                    b.HasOne("PersonalFinance.WebApi.Model.GanhoExtra", "GanhoExtra")
                        .WithMany("Competencia")
                        .HasForeignKey("GanhoExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.WebApi.Model.Gastos", "Gastos")
                        .WithMany("Competencia")
                        .HasForeignKey("GastosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.WebApi.Model.Patrimonio", "Patrimonio")
                        .WithMany("Competencia")
                        .HasForeignKey("PatrimonioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.WebApi.Model.Salario", "Salario")
                        .WithMany("Competencia")
                        .HasForeignKey("SalarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.WebApi.Model.Patrimonio", b =>
                {
                    b.HasOne("PersonalFinance.WebApi.Model.ContaBancaria", "ContaBancaria")
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.WebApi.Model.Investimentos", "Investimentos")
                        .WithMany()
                        .HasForeignKey("InvestimentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.WebApi.Model.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
